---
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: supercortex_flow
      POSTGRES_USER: flow_user
      POSTGRES_PASSWORD: flow_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "2222:8000"
    environment:
      DATABASE_URL: postgresql://flow_user:flow_pass@postgres:5432/supercortex_flow
      FLOW_ADMIN_TOKEN: ${FLOW_ADMIN_TOKEN}
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

volumes:
  postgres_data: 